version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_tutorial
      MYSQL_USER: user
      MYSQL_PASSWORD: ndyudev227
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/spring_tutorial?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_OPEN_IN_VIEW: false
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
    driver: bridge

volumes:
  mysql_data: